---
title: "bind_bt_bs"
author: "Shahar Chaikin"
date: "2025-05-06"
output: html_document
---

library
```{r}
library(tidyverse)
```

Load previos data and coords
```{r}
biotime_abund_slopes=read_rds("C:\\Users\\User\\Desktop\\research\\working groups\\iDiv_2024_25_sRED\\R\\sRED_demog_range_shifts\\stage_4_estimate_biotime_slopes/biotime_slopes.rds")

bioshifts_harmo_intersect_spat_cont=read_rds("C:\\Users\\User\\Desktop\\research\\working groups\\iDiv_2024_25_sRED\\R\\sRED_demog_range_shifts\\stage_2_intersect_data/bioshifts_harmo_intersect_spat_cont.rds")

bioshift_coords=read.csv("C:\\Users\\User\\Desktop\\research\\working groups\\iDiv_2024_25_sRED\\R\\sRED_demog_range_shifts\\stage_3_extract_bioshift_coords/layer_extents.csv")
```

add coords to bioshifts
```{r}
bioshifts_harmo_intersect_spat_cont=bioshifts_harmo_intersect_spat_cont %>% 
  left_join(bioshift_coords %>% 
              select(Source,cent_lat,cent_long),
            by="Source") %>% 
  select(-c(Genus,Species)) %>% 
  relocate(species_harmonized,.before = Hemisphere)
```

Join
```{r}
biotime_bioshift_merged_centroids=biotime_abund_slopes %>% 
  ungroup() %>% 
  rowwise() %>% 
  left_join(bioshifts_harmo_intersect_spat_cont,
            by="species_harmonized") %>% 
  filter(Position%in%"Centroid") %>% #Focus on centroid range shift velocities
  mutate(dist_BioTime_BioShift=(geosphere::distHaversine( #estimate distances in km
    p1=c(mean_long,mean_lat),
    p2=c(cent_long,cent_lat))/1000)) %>% 
  # For each BioTime population, keep only the closest BioShift record
  group_by(unique_id) %>% 
  filter(dist_BioTime_BioShift == min(dist_BioTime_BioShift)) %>% 
  # If multiple BioShift records have exactly the same minimum distance, keep just one
  slice(1) %>% 
  ungroup()

#How many shift estiamtes of the centoids per population?
biotime_bioshift_merged_centroids %>% 
  group_by(unique_id) %>% 
  summarise(n=n())

#Write
#write.csv(biotime_bioshift_merged_centroids,"biotime_bioshift_merged_centroids.csv",row.names = F)
```

#Summarise the data
Estimate slopes
```{r}
#Mean slope 
mean_slope=biotime_bioshift_merged_centroids %>% 
  ungroup() %>% 
  summarise(mean_slope=mean(slope),
            n=n(),
            ci_low=confint(data=biotime_bioshift_merged_centroids,
                           lm(slope~1))[,1],
            ci_high=confint(data=biotime_bioshift_merged_centroids,
                           lm(slope~1))[,2])
#Mean slope across realms
mean_slope_ecosystem=biotime_bioshift_merged_centroids %>% 
  group_by(Ecosystem) %>% 
  summarise(mean_slope=mean(slope),
            n=n(),
            ci_low=confint(data=biotime_bioshift_merged_centroids,
                           lm(slope~1))[,1],
            ci_high=confint(data=biotime_bioshift_merged_centroids,
                           lm(slope~1))[,2])

#Mean slope across phylum
mean_slope_Phylum=biotime_bioshift_merged_centroids %>% 
  group_by(Phylum) %>% 
  summarise(mean_slope=mean(slope),
            n=n(),
            ci_low=confint(data=biotime_bioshift_merged_centroids,
                           lm(slope~1))[,1],
            ci_high=confint(data=biotime_bioshift_merged_centroids,
                           lm(slope~1))[,2])

#Mean slope across class
mean_slope_Class=biotime_bioshift_merged_centroids %>% 
  group_by(Class) %>% 
  summarise(mean_slope=mean(slope),
            n=n(),
            ci_low=confint(data=biotime_bioshift_merged_centroids,
                           lm(slope~1))[,1],
            ci_high=confint(data=biotime_bioshift_merged_centroids,
                           lm(slope~1))[,2])

#Mean slope across Order
mean_slope_Order=biotime_bioshift_merged_centroids %>% 
  group_by(Order) %>% 
  summarise(mean_slope=mean(slope),
            n=n(),
            ci_low=confint(data=biotime_bioshift_merged_centroids,
                           lm(slope~1))[,1],
            ci_high=confint(data=biotime_bioshift_merged_centroids,
                           lm(slope~1))[,2])
```

#Plots
```{r}
ggplot(biotime_bioshift_merged_centroids)+
  geom_histogram(aes(x=slope,fill=Ecosystem))
```

